//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularDemoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class academic_detail
    {
        public int id { get; set; }
        public int student_id { get; set; }
        public string @class { get; set; }
        public string exam { get; set; }
        public string passout_year { get; set; }
        public string symbol_no { get; set; }
        public decimal obtained_marks { get; set; }
        public decimal obtained_percent { get; set; }
        public string division { get; set; }
        public decimal gpa { get; set; }
        public string school_college_name { get; set; }
    
        public virtual student_info student_info { get; set; }
    }
}
