//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularDemoProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MainEntities : DbContext
    {
        public MainEntities()
            : base("name=MainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<academic_detail> academic_detail { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<class_details> class_details { get; set; }
        public virtual DbSet<document_type> document_type { get; set; }
        public virtual DbSet<gender> genders { get; set; }
        public virtual DbSet<login_details> login_details { get; set; }
        public virtual DbSet<login_year_type> login_year_type { get; set; }
        public virtual DbSet<religion> religions { get; set; }
        public virtual DbSet<student_documents> student_documents { get; set; }
        public virtual DbSet<student_info> student_info { get; set; }
        public virtual DbSet<student_relatives_details> student_relatives_details { get; set; }
    }
}
