//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularDemoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_relatives_details
    {
        public int id { get; set; }
        public int class_id { get; set; }
        public int student_id { get; set; }
        public string relation { get; set; }
        public string remarks { get; set; }
    
        public virtual class_details class_details { get; set; }
        public virtual student_info student_info { get; set; }
    }
}
